### ISSUE TITLE
module restructuring

### ISSUE THREAD

**Issue by ukos-git** [ioistired/ps3-update-dl#5]
The current module only consists of an `__init_.py`.

A `__main__.py` is recommended to handle the execution of the module and the content from `__init__.py` should go to one or more other files to get a proper python module.

**Comment by ioistired** [comment]
There's already an `if __name__ == '__main__'` block so I'm not sure what this would accomplish. It was just one file before, and is only in a folder now to provide a home for the playstation-ca.crt file.

**Comment by ukos-git** [comment]
See https://docs.python-guide.org/writing/structure/

Package section:

A commonly seen issue is adding too much code to __init__.pyfiles.

**Comment by ioistired** [comment]
It's less than 200 lines, so not an issue.
